#!/bin/sh

if test -x /usr/bin/python3 && test -e /usr/lib/python3/dist-packages/django/bin/django-admin.py
then
    exec python3 /usr/lib/ngw/manage.py "$@"
elif test -x /usr/bin/python2.7 && test -e /usr/lib/python2.7/dist-packages/django/bin/django-admin.py
then
    exec python2.7 /usr/lib/ngw/manage.py "$@"
else
    echo "Cannot find installed version of python-django or python3-django." >&2
    exit 1
fi
