from django.conf.urls.defaults import *

groups_urlpatterns = patterns('',
    (r'^add$', 'ngw.core.views.contactgroup_edit', {'id': None}),
    (r'^(?P<id>\d+)/$', 'ngw.core.views.contactgroup_detail'),
    (r'^(?P<id>\d+)/edit$', 'ngw.core.views.contactgroup_edit'),
    (r'^(?P<id>\d+)/delete$', 'ngw.core.views.contactgroup_delete'),
    (r'^(?P<gid>\d+)/members/$', 'ngw.core.views.contactgroup_members'),
    (r'^(?P<gid>\d+)/members/vcards$', 'ngw.core.views.contactgroup_members', {'output_format': 'vcards'}),
    (r'^(?P<gid>\d+)/members/emails$',  'ngw.core.views.contactgroup_members', {'output_format': 'emails'}),
    (r'^(?P<gid>\d+)/members/csv$', 'ngw.core.views.contactgroup_members', {'output_format': 'csv'}),
    (r'^(?P<gid>\d+)/members/add$', 'ngw.core.views.contact_edit', {'cid':None}),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/$', 'ngw.core.views.contact_detail'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/vcard$', 'ngw.core.views.contact_vcard'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/edit$', 'ngw.core.views.contact_edit'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/pass$', 'ngw.core.views.contact_pass'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/pass_letter$', 'ngw.core.views.contact_pass_letter'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/delete$', 'ngw.core.views.contact_delete'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/membership$', 'ngw.core.views.contactingroup_edit'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/membershipinline$', 'ngw.core.views.contactingroup_edit_inline'),
    (r'^(?P<gid>\d+)/members/(?P<cid>\d+)/remove$', 'ngw.core.views.contactingroup_delete'),
    (r'^add_contacts_to$', 'ngw.core.views.contactgroup_add_contacts_to'),
    (r'^(?P<gid>\d+)/news/$', 'ngw.core.views.contactgroup_news'),
    (r'^(?P<gid>\d+)/news/add$', 'ngw.core.views.contactgroup_news_edit', {'nid':None}),
    (r'^(?P<gid>\d+)/news/(?P<nid>\d+)/$', 'django.views.generic.simple.redirect_to', {'url': '/contactgroups/%(gid)s/news/%(nid)s/edit'}),
    (r'^(?P<gid>\d+)/news/(?P<nid>\d+)/edit$', 'ngw.core.views.contactgroup_news_edit'),
    (r'^(?P<gid>\d+)/news/(?P<nid>\d+)/delete$', 'ngw.core.views.contactgroup_news_delete'),
    (r'^(?P<id>\d+)/mailman$', 'ngw.core.views.contactgroup_mailman'),
)

urlpatterns = patterns('',
    (r'^$', 'ngw.core.views.index'),
    
#    (r'^test$', 'ngw.core.views.test'),

    (r'^hook_change_password$', 'ngw.core.views.hook_change_password'),

    (r'^logout$', 'ngw.core.views.logout'),

    (r'^logs$', 'ngw.core.views.logs'),

    (r'^contacts/$', 'ngw.core.views.contact_list'),
    (r'^contacts/add$', 'ngw.core.views.contact_edit', {'gid':None, 'cid':None}),
    (r'^contacts/filter$', 'ngw.core.contactsearch.editfilter'),
    (r'^contacts/search/fields/(?P<kind>\w+)$', 'ngw.core.contactsearch.contactsearch_get_fields'),
    (r'^contacts/search/filters/(?P<field>\w+)$', 'ngw.core.contactsearch.contactsearch_get_filters'),
    (r'^contacts/search/params/(?P<field>\w+)/(?P<filtername>\w+)$', 'ngw.core.contactsearch.contactsearch_get_params'),
    (r'^contacts/search/filter_to_html$', 'ngw.core.contactsearch.contactsearch_filter_to_html'),
    (r'^contacts/make_login_mailing$', 'ngw.core.views.contact_make_login_mailing'),

    (r'^contacts/(?P<cid>\d+)/$', 'ngw.core.views.contact_detail'),
    (r'^contacts/(?P<cid>\d+)/edit$', 'ngw.core.views.contact_edit'),
    (r'^contacts/(?P<cid>\d+)/pass$', 'ngw.core.views.contact_pass', { 'gid': None }),
    (r'^contacts/(?P<cid>\d+)/pass_letter$', 'ngw.core.views.contact_pass_letter', { 'gid': None }),
    (r'^contacts/(?P<cid>\d+)/delete$', 'ngw.core.views.contact_delete', { 'gid': None }),
    (r'^contacts/(?P<cid>\d+)/vcard$', 'ngw.core.views.contact_vcard'),
    (r'^contacts/(?P<cid>\d+)/filters/$', 'ngw.core.views.contact_filters_list'),
    (r'^contacts/(?P<cid>\d+)/filters/add$', 'ngw.core.views.contact_filters_add'),
    (r'^contacts/(?P<cid>\d+)/filters/(?P<fid>\d+)$', 'ngw.core.views.contact_filters_edit'),

    (r'^contactgroups/$', 'ngw.core.views.contactgroup_list'),
    (r'^contactgroups/', include(groups_urlpatterns)),
    (r'^events/$', 'ngw.core.views.event_list'),
    (r'^events/', include(groups_urlpatterns)),

    (r'^contactfields/$', 'ngw.core.views.field_list'),
    (r'^contactfields/add$', 'ngw.core.views.field_edit', {'id': None}),
    (r'^contactfields/(?P<id>\d+)/$', 'django.views.generic.simple.redirect_to', {'url': '/contactfields/%(id)s/edit'}),
    (r'^contactfields/(?P<id>\d+)/edit$', 'ngw.core.views.field_edit'),
    (r'^contactfields/(?P<id>\d+)/moveup$', 'ngw.core.views.field_move_up'),
    (r'^contactfields/(?P<id>\d+)/movedown$', 'ngw.core.views.field_move_down'),
    (r'^contactfields/(?P<id>\d+)/delete$', 'ngw.core.views.field_delete'),

    (r'^choicegroups/$', 'ngw.core.views.choicegroup_list'),
    (r'^choicegroups/add$', 'ngw.core.views.choicegroup_edit', {'id': None}),
    (r'^choicegroups/(?P<id>\d+)/$', 'django.views.generic.simple.redirect_to', {'url': '/choicegroups/%(id)s/edit'}),
    (r'^choicegroups/(?P<id>\d+)/edit$', 'ngw.core.views.choicegroup_edit'),
    (r'^choicegroups/(?P<id>\d+)/delete$', 'ngw.core.views.choicegroup_delete'),

    (r'^pks/lookup$', 'ngw.core.gpg.lookup'),
)
