# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-03 15:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0011_choicecontactfield_datecontactfield_datetimecontactfield'
                '_emailcontactfield_filecontactfield_imagecon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choices',
                to='ngw.ChoiceGroup'),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='choice_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='ngw.ChoiceGroup',
                verbose_name='Choice group'),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='choice_group2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='second_choices_set',
                to='ngw.ChoiceGroup',
                verbose_name='Second choice group'),
        ),
        migrations.AlterField(
            model_name='contactfield',
            name='contact_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='ngw.ContactGroup',
                verbose_name='Only for'),
        ),
        migrations.AlterField(
            model_name='contactfieldvalue',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='values',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactfieldvalue',
            name='contact_field',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='values',
                to='ngw.ContactField'),
        ),
        migrations.AlterField(
            model_name='contactgroupnews',
            name='contact_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='news_set',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='contactingroup',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactingroup',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='contactmsg',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contactmsg',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='message_set',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='contactmsg',
            name='read_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='msgreader',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupingroup',
            name='father',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='direct_gig_subgroups',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='groupingroup',
            name='subgroup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='direct_gig_supergroups',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='groupmanagegroup',
            name='father',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_gmg_subgroups',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='groupmanagegroup',
            name='subgroup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_gmg_supergroups',
                to='ngw.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='log',
            name='contact',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
