# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0012_auto_20191003_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmsg',
            name='subject',
            field=models.CharField(default='No title', max_length=998,
                                   verbose_name='Subject'),
        ),
    ]
