# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0013_auto_20200507_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmsg',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
