# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0014_contactmsg_has_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='busy',
            field=models.BooleanField(
                default=False,
                help_text='Members are unavailable for other events'
                          ' at the same time',
                verbose_name='Busy'),
        ),
    ]
