# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0016_update_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='busy',
            field=models.BooleanField(
                default=False,
                help_text='Do the members become unavailable for other'
                          ' events at the same time?',
                verbose_name='Busy'),
        ),
    ]
