# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0017_auto_20201119_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='personnal_busy',
            field=models.BooleanField(
                default=False,
                help_text='This is a personnal unavailability period',
                verbose_name='Busy'),
        ),
    ]
