# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0018_contactgroup_personnal_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='personnal_busy',
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='perso_unavail',
            field=models.BooleanField(
                default=False,
                verbose_name='Personal unavailability'),
        ),
    ]
