# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 08:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0020_init_birthday_show_event_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingroup',
            name='subgroup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='direct_gig_supergroups',
                to='ngw.ContactGroup'),
        ),
    ]
