# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 12:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngw', '0021_auto_20210311_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixRoom',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('contact_group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='ngw.ContactGroup')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'matrix_room',
            },
        ),
    ]
